version: 2

multi-ecosystem-groups:
  project:
    schedule:
      interval: 'monthly'

updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: 'github-actions'
    directory: '/'
    patterns: ['*']
    multi-ecosystem-group: 'project'

  # Keep devontainer features up to date
  - package-ecosystem: 'devcontainers'
    directory: '/'
    patterns: ['*']
    multi-ecosystem-group: 'project'
