version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep devontainer features up to date
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
