# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# shellcheck disable=SC2034
ZSH_THEME="codespaces"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# shellcheck disable=SC2034
plugins=(docker git git-prompt vscode z)
# Plugins I'm not using currently: asdf docker-compose dotenv flutter gcloud golang helm heroku kubectl npm rust zsh_reload

# shellcheck disable=SC1091
source "${ZSH}/oh-my-zsh.sh"

# Alias for re-sourcing this file
# shellcheck disable=SC2139
alias src="source ${PROJECT_DIR}/.devcontainer/.zshrc"

# Bat alias
alias bat="batcat"

# Format shell files
alias format='shfmt --list --write --indent 2 --simplify ${PROJECT_DIR}'

# Run all tests
alias test="devcontainer features test --skip-autogenerated --skip-duplicated --preserve-test-containers"

# Run global tests
alias gtest="devcontainer features test --global-scenarios-only --preserve-test-containers"
