# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# shellcheck disable=SC2034
ZSH_THEME="codespaces"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# shellcheck disable=SC2034
plugins=(docker git git-prompt npm vscode z)
# Plugins I'm not using currently: asdf docker-compose dotenv flutter gcloud golang helm heroku kubectl rust zsh_reload

# shellcheck disable=SC1091
source "${ZSH}/oh-my-zsh.sh"

# Bat alias
alias bat="batcat"

# Run all checks
alias check='cd ${PROJECT_DIR} &&
  markdownlint-cli2 --config-file .markdownlint-cli2.jsonc &&
  prettier --check . &&
  shfmt --apply-ignore --diff --indent=2 --list --simplify --space-redirects .'

# Format shell files (uses single quotes to prevent expansion)
alias format='cd ${PROJECT_DIR} &&
  markdownlint-cli2 --fix --config-file .markdownlint-cli2.jsonc &&
  prettier --write . &&
  shfmt --apply-ignore --indent=2 --list --simplify --space-redirects --write .'

# Run global tests
alias gtest="devcontainer features test --global-scenarios-only"

# Alias for re-sourcing this file
# shellcheck disable=SC2139
alias src="source ${PROJECT_DIR}/.devcontainer/.zshrc"

# Run all tests
alias test='devcontainer features test --skip-autogenerated --skip-duplicated'
